<?php
//====================================Emoticons char===========================================
$em_char = array(
    "😀",
    "😁",
    "😂",
    "😃",
    "😄",
    "😅",
    "😆",
    "😉",
    "😊",
    "😋",
    "😎",
    "😍",
    "😘",
    "😗",
    "😙",
    "😚",
    "☺",
    "🙂",
    "🤗",
    "🤔",
    "😐",
    "😑",
    "😶",
    "🙄",
    "😏",
    "😣",
    "😥",
    "😮",
    "🤐",
    "😯",
    "😪",
    "😫",
    "😴",
    "😌",
    "🤓",
    "😛",
    "😜",
    "😝",
    "😒",
    "😓",
    "😔",
    "😕",
    "🙃",
    "🤑",
    "😲",
    "☹",
    "🙁",
    "😖",
    "😞",
    "😟",
    "😤",
    "😢",
    "😭",
    "😦",
    "😧",
    "😨",
    "😩",
    "😬",
    "😰",
    "😱",
    "😳",
    "😵",
    "😡",
    "😠",
    "😇",
    "😷",
    "🤒",
    "🤕",
    "😈",
    "👿",
    "👻",
    "🤖",
    "💩",
    "👣",
    "👀",
    "👁",
    ":eye🗨:",
    "👅",
    "👄",
    "💋",
    "💘",
    "❤",
    "💓",
    "💔",
    "💕",
    "💖",
    "💗",
    "💙",
    "💚",
    "💛",
    "💜",
    "💝",
    "💞",
    "💟",
    "❣",
    "💌",
    "💤",
    "💢",
    "💨",
    '🐸',
    '🐍',
    '♨',
    '🚬',
);
//====================================Emoticons img path=======================================
$em_img = array(
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f600.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f601.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f602.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f603.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f604.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f605.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f606.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f609.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f60a.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f60b.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f60e.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f60d.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f618.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f617.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f619.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f61a.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."263a.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f642.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f917.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f914.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f610.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f611.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f636.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f644.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f60f.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f623.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f625.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f62e.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f910.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f62f.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f62a.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f62b.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f634.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f60c.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f913.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f61b.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f61c.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f61d.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f612.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f613.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f614.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f615.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f643.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f911.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f632.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."2639.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f641.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f616.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f61e.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f61f.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f624.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f622.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f62d.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f626.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f627.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f628.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f629.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f62c.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f613.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f631.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f633.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f635.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f621.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f620.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f607.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f637.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f912.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f915.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f608.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f47f.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f47b.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f916.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f4a9.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f463.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f440.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f441.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f441-1f5e8.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f445.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f444.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f48b.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f498.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."2764.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f493.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f494.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f495.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f496.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f497.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f499.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f49a.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f49b.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f49c.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f49d.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f49e.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f49f.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."2763.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f48c.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f4a4.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f4a2.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f4a8.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f438.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f40d.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."2668.png' />",
    "<img style='box-shadow: none;width:22px;height:22px;' src='"."$em_img_path"."1f6ac.png' />",
);
?>